library:
  visible: false
source:
  visible: true
  percentage: 0.5999954245973645
board:
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_edit_board: false
    can_view_size_section: false
    can_view_attire_section: true
    can_toggle_visibility: false
  active: 1
  initial_board_source: selected
execution_speed:
  user_permissions:
    can_change_speed: true
  active: instantaneous
attire:
  user_permissions:
    can_toggle_visibility: true
  active: Flappy
  visible: true
blocks:
  visible:
    - Poner
    - Mover
    - Sacar
    - MisProcedimientos
    - RepeticionSimple
    - Numero 
    - Color
    - Direccion
    - procedures_defnoreturn
    - procedures_defreturnsimple
    - OperadorNumerico
    - AlternativaSimple
    - puedeMover
    - hayBolitas
    - BOOM
    - RepeticionCondicional
    - not
    - opuesto
    - DefinicionDeAsociacionDeTeclaEspecial
  disabled: []
name: Moviendo a Flappy

