name: Flappy
rules:
  - { image: cielo.png,       when: { blue:   1, black:    0, red: 0, green: 0 } } 
  - { image: fondo.png,       when: { blue:   0, black:    0, red: 0, green: 0 } } 
  - { image: pajarito.png,    when: { blue:   0, black:    1, red: 0, green: 0 } } 
  - { image: tuboMedio.png,   when: { blue:   0, black:    0, red: 0, green: 1 } } 
  - { image: tuboPuntaAbajo.png,       when: { blue:   0, black:    0, red: 0, green: 2 } } 
  - { image: tuboPuntaArriba.png,       when: { blue:   0, black:    0, red: 0, green: 3 } } 
  - { image: Gana.png,                   when: { blue:   0, black:    2, red: 0, green: 0 } } 


  
